#!/bin/zsh
# The canonical curation at the 2026-08-22 config:
#   book      6 · 0.25 · 21 · 0 · 4.0 · 0.10
#   curation  min_bundle_articles 1 · max_events 0 (UNCAPPED) · max_event_scans 6
#
# --decisions IS REQUIRED. CBT reads five files from a run dir -- curator_metrics.json, journal.json,
# firehose_scans.csv, decisions.jsonl and panel.csv -- and only the first three are written
# unconditionally. Omitting --decisions on the 2026-08-21 mb sweep cost CBT's three scout funnel bars
# and panels 12/14/16/17, and the proposed-and-culled candidates are recoverable from nowhere else.
# panel.csv is frozen afterwards by sweep_optimizer --panel-only (no grid, just the price fetch), so
# CBT is reproducible and prices identically to SBT.
#
# NAMED v18, not by knob value: mb1/mb2/mb3 encode min_bundle_articles, and a name that asserts a
# setting it does not have is the same class of error as the stale journal inside cbt_3yr_v9.
#
# DO NOT EDIT THIS FILE WHILE IT RUNS -- zsh reads scripts by byte offset.
set -u
cd "$(dirname "$0")/.."
LOG=/tmp/v18.log
print -r -- "=== curate START $(date -u +%FT%TZ) ===" >> "$LOG"
.venv/bin/python scripts/backtest_gdelt.py \
    --start 2023-08-11 --end 2026-07-26 \
    --corpus data/backtest_3yr_v5 \
    --out data/cbt_3yr_v18 \
    --decisions >> "$LOG" 2>&1
print -r -- "=== curate DONE rc=$? $(date -u +%FT%TZ) ===" >> "$LOG"
print -r -- "=== panel START $(date -u +%FT%TZ) ===" >> "$LOG"
.venv/bin/python scripts/sweep_optimizer.py --run data/cbt_3yr_v18 --panel-only >> "$LOG" 2>&1
print -r -- "=== panel DONE rc=$? $(date -u +%FT%TZ) ===" >> "$LOG"
print -r -- "=== ALL COMPLETE $(date -u +%FT%TZ) ===" >> "$LOG"
