#!/bin/zsh
# A REPEAT of the canonical curation config (min_bundle_articles=2), for two purposes:
#   1. a THIRD independent sweep, to test whether the cross-sweep config survives (the two-way
#      intersection is only 1.7x chance, which is real but weak);
#   2. --decisions this time, which mb1/mb2/mb3 were launched without -- proposed-and-culled
#      candidates are persisted nowhere else, so CBT's funnel bars and panels 12/14/16/17 need it.
# Also the first clean same-config noise measurement on the completed corpus: v9-vs-mb1 is
# contaminated by the wayback text change.
# DO NOT EDIT THIS FILE WHILE IT RUNS -- zsh reads scripts by byte offset, and editing the previous
# sweep driver mid-run made the shell resume at a stale offset and execute fragments ("ython").
set -u
cd "$(dirname "$0")/.."
LOG=/tmp/mb2rep.log
print -r -- "=== curate START $(date -u +%FT%TZ) ===" >> "$LOG"
.venv/bin/python scripts/backtest_gdelt.py \
    --start 2023-08-11 --end 2026-07-26 \
    --corpus data/backtest_3yr_v5 \
    --out data/cbt_3yr_mb2rep \
    --min-bundle-articles 2 \
    --decisions >> "$LOG" 2>&1
print -r -- "=== curate DONE rc=$? $(date -u +%FT%TZ) ===" >> "$LOG"
print -r -- "=== sweep START $(date -u +%FT%TZ) ===" >> "$LOG"
.venv/bin/python scripts/sweep_optimizer.py --run data/cbt_3yr_mb2rep \
    --out data/sweep_mb2rep.json >> "$LOG" 2>&1
print -r -- "=== sweep DONE rc=$? $(date -u +%FT%TZ) ===" >> "$LOG"
print -r -- "=== ALL COMPLETE $(date -u +%FT%TZ) ===" >> "$LOG"
